packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@eggjs/bin'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
